### ISSUE TITLE
Why is this needed?

### ISSUE THREAD

**Issue by gdalsnes** [manuelroemer/IsExternalInit#1]
I don't understand.
I have a netstandard2.0 assembly using LangVersion 9.0 and with this added:
namespace System.Runtime.CompilerServices
{
	internal class IsExternalInit { }
}
Then init works.

I can reference this assembly from net5.0 assemblies (using default LangVersion 9.0) and from .NET framework 4.7.2 using default LangVersion (assume 7.3). So why would I need this?

**Comment by gdalsnes** [comment]
Hmm, I guess if I wanted to multi target the assembly that is using init for eg. netstandard2.0 and net5.0, I would need something like this.

**Comment by manuelroemer** [comment]
As you said, multitargeting is a reason for this. For me personally, I also prefer the simplicity of a quick package installation in comparison to copy and pasting (or even writing) the class myself. Using the package furthermore ensures that the code file doesn’t appear in your project in most cases.
But at the end of they day the package is just there for convenience and can, as you wrote, easily be replaced with a manual class declaration. By all means, use whatever suits your requirements.

**Comment by manuelroemer** [comment]
As an example, in several of my solutions I'm having multiple projects which want to use the new init feature. Instead of redeclaring the IsExternalInit class in every single project in the solution, I just reference the package once in a global Directory.Build.props file and can then use the features in every project, no matter what they are targeting, with just 3 lines of (configuration) code.

**Comment by manuelroemer** [comment]
Closing this for now. If you’ve got any follow-up questions, don’t hesitate to ask!
